### ISSUE TITLE
Accepting Ints as Doubles in BSON

### ISSUE THREAD

**Issue by pulewicz** [AVSystem/scala-commons#414]
Hi,

We're working with a an existing database, where doubles are sometimes written as ints(example: `10` instead of `10.0`). This causes the following problem: `Encountered BsonValue of type INT32, expected DOUBLE`.

I was thinking about how to approach this properly. I got 2 working solutions, but I'm not 100% happy with either of them.

1. Write a custom codec for `Double`, example:

```
object DoubleCodec extends GenCodec.SimpleCodec[Double] {

  override def readSimple(input: SimpleInput): Double = {

    try input.readDouble()
    catch {
      case NonFatal(_) => // catching something more specific will be better
        input.readInt().toDouble
    }
  }

  override def writeSimple(output: SimpleOutput, value: Double): Unit = output.writeDouble(value)

  override def nullable: Boolean = false
}

```

What I don't like here is that we have to use a try-catch block(or Scala `Try`, but it'll be the same thing under the hood), because `SimpleInput` only has `readX` methods, and nothing to check the type before trying to read it.

2. Make a change in the input classes, this will require a change in the lib. This seems more proper, but again there is a catch:
- We either have to accept ints, but always produce doubles in outputs, which is kind-of inconsistent (this is not a problem in our case)
- Or we have to accept ints, and sometimes produce ints in outputs. This is also fine in our case, but it breaks the compatibility of the library.

For the second approach, I crated a draft PR: https://github.com/AVSystem/scala-commons/pull/413 (needs more tests and probably some other improvements, but just posting it here as a base for a better solution)

Do you know any other, better way?

Regards,
Paweł Ulewicz.

**Comment by pulewicz** [comment]
Hi again,

Thank you for reviewing and merging my changes. Is there anything else to be done to include it in the next version? And when do the new version get released? 

Regards,
Paweł Ulewicz.

**Comment by ghik** [comment]
Hi, 2.6.1 is already there
