### ISSUE TITLE
Cannot pull single element by value in Mongo update

### ISSUE THREAD

**Issue by AvaPL** [AVSystem/scala-commons#416]
I have a write command like this:

```scala
MongoWrite.UpdateMany(
  filter = MyEntity.ref(_.someField).in(listOfFields),
  update  = MyEntity.ref(_.listOfUuids).pull(_ === uuid),
  setupOptions = _.upsert(true)
)
```

Running this write results in an exception from Mongo:
```
Bulk write operation error on server localhost:27017. Write errors: [BulkWriteError{index=0, code=2, message='unknown top level operator: $eq', details={}}]
```

I assume that it constructs a similar filter like in this SO question: https://stackoverflow.com/questions/49617088/how-to-remove-element-from-array-in-mongodb

Is it possible to construct an update that doesn't have this issue? Currently I've found two workarounds:
- `.pullAll(uuid)`
- `.pull(_.in(uuid))`

**Comment by ghik** [comment]
I can't reproduce this problem with MongoDB 5.0
What server version are you using? Are you bound to that version?

**Comment by AvaPL** [comment]
I'm using 4.0.27. I'm bound to that version, but I've tried with Mongo 5 and it works fine. Given the fact that I have a workaround for my version and it does not have a significant performance impact, I think that there is no need to alter in the library. Thank you for quick response.
