### ISSUE TITLE
Cannot materialize nested ADTs by a single call of GenCodec.materializeRecursively

### ISSUE THREAD

**Issue by plokhotnyuk** [AVSystem/scala-commons#63]
Currently, if a field of the top-level ADT has reference to another ADT, than both ADTs should be materialized recursively.
Please, see the following line for a use case: https://github.com/plokhotnyuk/jsoniter-scala/pull/127/files#diff-23a38b9df42d1a3a0e654c5532d6f666R37

**Comment by ghik** [comment]
Looks like it's an omission in flat sealed hierarchy codecs (the ones that use `@flatten` annotation). Will be fixed in next version.

**Comment by ghik** [comment]
Fixed in 1.28.0
