### ISSUE TITLE
Parsed BigDecimal is not limited for a scale value and has an UNLIMITED math context that is unsafe for open systems

### ISSUE THREAD

**Issue by plokhotnyuk** [AVSystem/scala-commons#65]
The code bellow can grab CPU core for several minutes and then will throw an out of memory error:
```
JsonStringInput.read[BigDecimal]("\"1e2000000000\"") + 1
```
More details: https://github.com/scala/bug/issues/10882

**Comment by ghik** [comment]
Fixed as part of #66 in #74, `JsonStringInput` uses `BigDecimal.defaultMathContext` (`DECIMAL128`) which can be adjusted using `JsonOptions`.
