### ISSUE TITLE
Input/Output native support for BigInteger and BigDecimal

### ISSUE THREAD

**Issue by ghik** [AVSystem/scala-commons#68]
Add `writeBigInteger` and `writeBigDecimal` methods to `Output` trait.
Add `readBigInteger` and `readBigDecimal` methods to `Input` trait.

**Comment by ghik** [comment]
This along with configurable `MathContext` in #66 should solve #65

**Comment by plokhotnyuk** [comment]
Also, limits for the scale should be configurable (with some defaults like ±300 provided) to resolve #65
