### ISSUE TITLE
Compilation error when importing GenCodec in Scala 2.11

### ISSUE THREAD

**Issue by plokhotnyuk** [AVSystem/scala-commons#75]
Got a following error [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/7aa20826271d03262b734caa40d818bda5f725d3/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/AVSystemCodecs.scala#L6) with v1.28.2:
```
[error] /home/travis/build/plokhotnyuk/jsoniter-scala/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/AVSystemCodecs.scala:6:8: Symbol 'term com.github.ghik' is missing from the classpath.
[error] This symbol is required by ' <none>'.
[error] Make sure that term ghik is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'SharedExtensions.class' was compiled against an incompatible version of com.github.
[error] import com.avsystem.commons.serialization.GenCodec
[error] 
``` 
Perhaps the cause is using of the `com.github.ghik.silencer.silent` annotation in `GenCodec` sources, and declaration the `provided` scope for the `silencer-lib` dependency:
http://search.maven.org/remotecontent?filepath=com/avsystem/commons/commons-macros_2.11/1.28.2/commons-macros_2.11-1.28.2.pom

**Comment by plokhotnyuk** [comment]
W/A is to add the missing dependency:
```
"com.github.ghik" %% "silencer-lib" % "0.6",
```

**Comment by ghik** [comment]
Fixed in [silencer](https://github.com/ghik/silencer/commit/424feac67b0bdf8d6c6f9b8f2f743edad230f2d6) and [updated](https://github.com/AVSystem/scala-commons/commit/35408786b3540f05794b8f47a293dfeca991cca0) in `commons`.
